url: https://pubinv.github.io/optical-linear-sensor
repourl: https://github.com/PubInv/optical-linear-sensor
projecttitle: "Optical Linear Sensor"
featuretitle: "Optical Linear Sensor"
featurelink: https://pubinv.github.io/optical-linear-sensor